"""Compute statistical description of datasets."""

import multiprocessing
import multiprocessing.pool
from typing import Tuple

import numpy as np
import pandas as pd
from tqdm import tqdm
from visions import VisionsTypeset

from ydata_profiling.config import Settings
from ydata_profiling.model.summarizer import BaseSummarizer
from ydata_profiling.model.summary import describe_1d, get_series_descriptions
from ydata_profiling.model.typeset import ProfilingTypeSet
from ydata_profiling.utils.dataframe import sort_column_names


def _is_cast_type_defined(typeset: VisionsTypeset, series: str) -> bool:
    """```python
def _is_cast_type_defined(typeset: VisionsTypeset, series: str) -> bool:
    """
    Check if the specified series is defined in the type schema of the given typeset.

    This function verifies if the provided typeset is an instance of ProfilingTypeSet
    and whether the specified series exists within its type schema.

    Args:
        typeset (VisionsTypeset): The typeset to check for the defined series.
        series (str): The series name to look for in the type schema.

    Returns:
        bool: True if the typeset is an instance of ProfilingTypeSet and 
              the series is found in its type schema, otherwise False.
    """
    return isinstance(typeset, ProfilingTypeSet) and series in typeset.type_schema"""
    return isinstance(typeset, ProfilingTypeSet) and series in typeset.type_schema


@describe_1d.register
def pandas_describe_1d(
    config: Settings,
    series: pd.Series,
    summarizer: BaseSummarizer,
    typeset: VisionsTypeset,
) -> dict:
    """Describe a series (infer the variable type, then calculate type-specific values).

    Args:
        config: report Settings object
        series: The Series to describe.
        summarizer: Summarizer object
        typeset: Typeset

    Returns:
        A Series containing calculated series description values.
    """

    # Make sure pd.NA is not in the series
    series = series.fillna(np.nan)

    has_cast_type = _is_cast_type_defined(typeset, series.name)
    cast_type = str(typeset.type_schema[series.name]) if has_cast_type else None

    if has_cast_type and not series.isna().all():
        vtype = typeset.type_schema[series.name]

    elif config.infer_dtypes:
        # Infer variable types
        vtype = typeset.infer_type(series)
        series = typeset.cast_to_inferred(series)
    else:
        # Detect variable types from pandas dataframe (df.dtypes).
        # [new dtypes, changed using `astype` function are now considered]
        vtype = typeset.detect_type(series)

    typeset.type_schema[series.name] = vtype
    summary = summarizer.summarize(config, series, dtype=vtype)
    # Cast type is only used on unsupported columns rendering pipeline
    # to indicate the correct variable type when inference is not possible
    summary["cast_type"] = cast_type

    return summary


@get_series_descriptions.register
def pandas_get_series_descriptions(
    config: Settings,
    df: pd.DataFrame,
    summarizer: BaseSummarizer,
    typeset: VisionsTypeset,
    pbar: tqdm,
) -> dict:
    """config: Settings,
    df: pd.DataFrame,
    summarizer: BaseSummarizer,
    typeset: VisionsTypeset,
    pbar: tqdm,
) -> dict:
    """
    Generate descriptive statistics for each column in a pandas DataFrame.

    This function utilizes parallel processing to compute descriptive statistics
    for each series (column) in the provided DataFrame. The results are returned
    in a dictionary where the keys are the column names and the values are the
    corresponding descriptions generated by the specified summarizer.

    Args:
        config (Settings): Configuration settings, including pool size for parallel processing.
        df (pd.DataFrame): The DataFrame containing the data to be described.
        summarizer (BaseSummarizer): An instance of a summarizer used to generate statistics.
        typeset (VisionsTypeset): Typeset for visualizing the data descriptions.
        pbar (tqdm): A tqdm progress bar instance for tracking progress during computation.

    Returns:
        dict: A dictionary mapping column names to their respective descriptions.

    Notes:
        If the specified pool size is less than or equal to 0, it defaults to the number
        of available CPU cores. The function handles single-threaded execution and 
        multi-threaded execution based on the pool size defined in the configuration.
        The original order of columns is preserved in the result.
    """
    def multiprocess_1d(args: tuple) -> Tuple[str, dict]:
        """Wrapper to process series in parallel.

        Args:
            column: The name of the column.
            series: The series values.

        Returns:
            A tuple with column and the series description.
        """
        column, series = args
        return column, describe_1d(config, series, summarizer, typeset)

    pool_size = config.pool_size

    # Multiprocessing of Describe 1D for each column
    if pool_size <= 0:
        pool_size = multiprocessing.cpu_count()

    args = [(name, series) for name, series in df.items()]
    series_description = {}

    if pool_size == 1:
        for arg in args:
            pbar.set_postfix_str(f"Describe variable:{arg[0]}")
            column, description = multiprocess_1d(arg)
            series_description[column] = description
            pbar.update()
    else:
        # TODO: use `Pool` for Linux-based systems
        with multiprocessing.pool.ThreadPool(pool_size) as executor:
            for i, (column, description) in enumerate(
                executor.imap_unordered(multiprocess_1d, args)
            ):
                pbar.set_postfix_str(f"Describe variable:{column}")
                series_description[column] = description
                pbar.update()

        # Restore the original order
        series_description = {k: series_description[k] for k in df.columns}

    # Mapping from column name to variable type
    series_description = sort_column_names(series_description, config.sort)
    return series_description
